# This is a basic workflow to help you get started with Actions

name: Release CI

on:
  push:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  

  build-and-release-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: 3.19.5
          channel: stable
      - name: Install project dependencies
        run: flutter pub get
        working-directory: ./navigator_test2
      - name: Build artifacts
        run: flutter build windows --release -v
        working-directory: ./navigator_test2
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: exe-windows.zip
          directory: D:\a\pruebas_flutter\pruebas_flutter\navigator_test2
          # directory: D:\a\pruebas_flutter\pruebas_flutter\navigator_test2\build\windows\x64\runner\Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: D:\a\pruebas_flutter\pruebas_flutter\navigator_test2
          # path: D:\a\pruebas_flutter\pruebas_flutter\navigator_test2\build\windows\x64\runner\Release
          name: exe-windows.zip
   
